services:
  db:
    image: postgres:17
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: lmnotes
    ports:
      - 5433:5432
    volumes:
      - db_data:/var/lib/postgresql/data

  frontend:
    build:
      context: lmnotes
      dockerfile: Dockerfile
    ports:
      - 3000:3000

  backend:
    build:
      context: api
      dockerfile: Dockerfile
    ports:
      - 3001:3001
      

volumes:
  db_data:
